package main

import (
  "os"
  "log"
  "github.com/handicraftsman/gopack/lib"
)


func packGenerate() {
  str := "" +
    "// This file is generated by gopack (https://github.com/handicraftsman/gopack)\n" +
    "// and contains package-info (from used Packfile) and embedded data (if any)\n" +
    "package " + procPackage + "\n\n" +
    "var Name string = \"" + procProject + "\"\n" +
    "var Version string = \"" + procVersion + "\"\n" +
    "var Package string = \"" + procPackage + "\"\n" +
    "var GoPack string = \"" + Version + "\"\n\n" +
    procVarCode 

  exists, err := gopack.FileExists("./packdata.go")
  if err != nil {
    log.Panic(err)
  }

  if !exists {
    os.Remove("./packdata.go")
  }

  file, err := os.Create("./packdata.go")
  if err != nil {
    log.Panic(err)
  }

  file.WriteString(str)

  file.Close()
}

