// This file is generated by gopack (https://github.com/handicraftsman/gopack)
// and contains package-info (from used Packfile) and embedded data (if any)
package main

var Name string = "GoPack"
var Version string = "0.0.1-dev"
var Package string = "main"
var GoPack string = "0.0.1-dev"

